#!/bin/sh
################################################################################
#                                                                              #
#                             SIT-ROUTING by KB19                              #
#                            ----------------------                            #
#                             v0.1.0 -- 2018/04/21                             #
#                                                                              #
# Deletes routes created by 6in4 tunnels.                                      #
#                                                                              #
# UCI config: [NONE]                                                           #
# Executable: /etc/hotplug.d/iface/59-sit-routing                              #
#                                                                              #
################################################################################

. /lib/functions.sh && \
. /lib/functions/network.sh || \
exit 1

if [ "$ACTION" = "ifup" -a ! -z "$INTERFACE" ]
then
	config_load "network"
	config_get proto "$INTERFACE" proto
	config_get ipaddr "$INTERFACE" ipaddr
	config_get peeraddr "$INTERFACE" peeraddr

	if [ "$proto" = "6in4" -a ! -z "$ipaddr" -a ! -z "$peeraddr" ] \
	&& __network_ifstatus "iface" "" "[@['ipv4-address'][*]['address']='$ipaddr'].interface"
	then
		network_get_device "device" "$iface"
		network_get_gateway "gateway" "$iface"
		__network_ifstatus "metric" "$iface" ".metric"

		if ip -4 route del "$peeraddr/32" via "$gateway" dev "$device" proto "static" metric "${metric:-0}" 2>/dev/null
		then logger -p "user.info" -t "sit-routing[$$]" -s "Deleted route to $peeraddr, created by 6in4 interface $INTERFACE."
		fi
	fi
fi
